### ISSUE TITLE
Provide `throws` in addition to `runs` and `returns`

### ISSUE THREAD

**Issue by ankushg** [Kodein-Framework/MocKMP#19]
When mocking an interface, I'd like to be able to say

```kt
every { 
	mock.method(isAny())
} throws {
  Exception("something happened")
}
```

and then 
1. verify that parameters matched, and 
2. ideally, also verify that the exception was thrown.

Currently, if you use `runs` to `throw Exception()`, it looks like MocKMP does **neither**.  There seems to be no way to even check that the method was called with the expected parameters because the exception causes the logging to be skipped.

**Comment by SalomonBrys** [comment]
Exceptions are now supported in `1.6.0`.

```kotlin
expect { mock.something() } runs { throw MyException() }

//...

verify {
    val ex = threw<MyException> { mock.something() }
}
```

The new associated verification functions `threw` and `called` are documented here: https://github.com/Kodein-Framework/MocKMP#verifying-exception-thrown

Note that the decision was made not to add a specific `expect {} throws` syntax.
This is because:
* `expect { m.s() } throws MyException()` (without accolades) would create exceptions with incorrect stack traces.
* `expect { m.s() } throws { MyException() }` (with accolades) opens to bad practice of treating `throws` as `runs` and putting some behaviour in the block before the exception creation.
* Using `runs` also enables the use of standard library exception functions, such as `error`, `require` and `check`.
